
name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Format
        run: test -z "$(gofmt -l .)" || (echo "Code is not formatted. Please run gofmt." && exit 1)

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.1
          args: --config=.golangci.yml

      - name: Test and coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Check test coverage
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
          if (( $(echo "$coverage < 70" | bc -l) )); then
            echo "Test coverage is below 70% (${coverage}%)"
            exit 1
          else
            echo "Test coverage is sufficient (${coverage}%)"
          fi

      - name: Check for code repetition
        run: |
          go install github.com/h-ono/gocpd@v0.2.1
          gocpd -t 10 .
